### ISSUE TITLE
`address` field disappears after changing `address` to `profession`

### ISSUE THREAD

**Issue by ericlikedis** [piazzai/hacked-jekyll#2]
Here is what the YML looks like currently

![CleanShot 2023-08-22 at 22 01 14@2x](https://github.com/piazzai/hacked-jekyll/assets/48847865/32e2925a-c127-4074-89f7-19f5cc2c4542)

Here is what it looks like on the page

![CleanShot 2023-08-22 at 22 03 29@2x](https://github.com/piazzai/hacked-jekyll/assets/48847865/f99e192f-6afb-4e3e-9c17-223a3d01ae2f)

**Comment by ericlikedis** [comment]
This might just be something I am unable to change, but I would like to be able to change the field to be something other than "address" for more customizability.

**Comment by piazzai** [comment]
Hi! You're certainly able to change this, though it requires a bit more work. By changing `address` to `profession` in the config file, you've done half the work. The other half is changing `_layouts/home.html`. Take a look at lines 33-46:

```
<div class="block">
    {% if site.json.address %}
    {% if site.json.address.first %}
    <p><span class="array-key">address</span></p>
    <div class="array">
      {% for i in site.json.address %}
      <p class="array-attr">{{ i }}</p>
      {% endfor %}
    </div>
    {% else %}
    <p><span class="key">address</span><span class="attr">{{ site.json.address }}</span></p>
    {% endif %}
    {% endif %}
  </div>
```

Just substitute every instance of `address` for `profession`, and you're done. Please feel free to reopen the issue if that doesn't achieve exactly what you want.
