### ISSUE TITLE
Error when adding remote

### ISSUE THREAD

**Issue by rriggin** [piazzai/hacked-jekyll#3]
Hi there. I get this permission error when trying to connect this to a github remote repo.  Did I miss a step?

{23-09-19 17:36}Ryans-MBP:~/Dev/rriggin.github.io@main ryanriggin% git push -u origin main
ERROR: Permission to piazzai/hacked-jekyll.git denied to rriggin.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
{23-09-19 17:36}Ryans-MBP:~/Dev/rriggin.github.io@main ryanriggin%

**Comment by piazzai** [comment]
Hi! I'm not entirely sure, but `ERROR: Permission to piazzai/hacked-jekyll.git denied to rriggin.` makes me think you're trying to push your changes to the template's repository instead of your own fork. You should be pushing to `rriggin/hacked-jekyll`, not `piazzai/hacked-jekyll`.
