### ISSUE TITLE
Added the blog functionality to this amazing theme 

### ISSUE THREAD

**Issue by zepvalue** [piazzai/hacked-jekyll#4]
https://github.com/zepvalue/zepvalue.github.io 

You can check this Repo with the blog feature added, I still have to add the footer to give you credit but I really enjoy this theme 

As you can see there is a bit of work around github-pages gem and extra gems needed to make it work properly with sass, maybe even manage it a bit better 

Grazie mille collega :)

**Comment by piazzai** [comment]
I'm very happy to hear you like the theme. Grazie a te!
